version: "3.7"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123123aa
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-combine

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 123123aa
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8060:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - postgres-combine


networks:
  postgres-combine:

volumes:
  postgres-data:
  pgadmin-data: